### ISSUE TITLE
Add ability to setup flash messages on action success

### ISSUE THREAD

**Issue by klimov-paul** [yii2tech/admin#9]
Such actions like 'delete' often requires a flash message being set, indicating action result.

**Comment by klimov-paul** [comment]
Resolved by commit 6e1ff6a06c4ceebd3f18f5ba2000e6c31b4548ed

**Comment by klimov-paul** [comment]
Advanced 9f912c5baf425c6c043796671178884d5c9fd929

**Comment by loveorigami** [comment]
Hi, Pavel
I am watch your yii2tech/admin repo.
And I see also your last commit.

I am also think about "How better display Flash message?". 
I am write module
https://github.com/loveorigami/yii2-notification-wrapper
for display messages from stand-alone and ajax (pjax, etc...) actions.

Hope, It will be usefull for this admin.

Regards

**Comment by klimov-paul** [comment]
Flash messages representation are covered by `Alert` widget:
https://github.com/yii2tech/admin/blob/master/widgets/Alert.php

Still you are free to use any other solution for this, `yii2tech/admin` does not restict this.
